language: node_js
node_js:
  - "0.12.4"

addons:
  code_climate:
    repo_token: d92f8a06d44c9ed8ae407addfff0b3ec22040ed8cca6686f5b3ffbeda1e2c780

script:
  - "npm run test-single-run"

after_script:
  - "./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage.info"
