language: node_js
node_js:
  - "0.12.4"
addons:
  code_climate:
    repo_token: d92f8a06d44c9ed8ae407addfff0b3ec22040ed8cca6686f5b3ffbeda1e2c780
script:
  - "npm run test-single-run"
after_script:
  - "./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage.info"
notifications:
  email: false
  hipchat:
    rooms:
      secure: "UvS5UdLDKhhAtfLj6AszfeWXsa2avrN5s1vItQ4wd6lcagSGTN1nbo6tUJ4wuD5ao9OCNOe+X6VxvRtWkZjYzujxknn9DkRh+CFoJPH+gfcsSVG34fKlCodcPIYne/ondMxqNfwZJRvI/5wYYhSmAZ0AoK9RUbXNWycBRAdG3qk="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    notify: true
